[browser]
gatherUsageStats = false
serverAddress = "localhost"

[server]
headless = true
port = 8502
enableCORS = false
enableXsrfProtection = true

[client]
toolbarMode = "minimal"
showErrorDetails = true

[theme]
base = "light"
primaryColor = "#166534"
backgroundColor = "#F5F4F0"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1a2332"
font = "sans serif"
